// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyoxauztcrpdheumyubd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5b3hhdXp0Y3JwZGhldW15dWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NzM4OTcsImV4cCI6MjA2MDI0OTg5N30.2MJ2HLQfOrvf1_cCI1M353ThZ131Vwz6nlaygsHTFQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);